apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: premium-customer-

resources:
- namespace.yaml
- https://github.com/giovannibaratta/argocd-deploy//apps-manifests/awesome-app

patches:
- path: https://raw.githubusercontent.com/giovannibaratta/argocd-deploy/main/argocd/patches/add-custom-labels.json
  target:
    kind: Pod